### ISSUE TITLE
support for annotations?

### ISSUE THREAD

**Issue by ahillio** [lauft/timew-report#4]
It doesn't look like this makes time annotations available.... is that so?
What would it take to do that?  would it simply require editing the `TimeWarriorInterval` class?  I tried adding:
```
    def annotation(self):
        return self.__annotation
```
to the class definition before discovering my next hurdle of the pip module system and installing a fork to test of if this works.

**Comment by ahillio** [comment]
Annotations are requested https://github.com/GothenburgBitFactory/timewarrior/issues/266 and I was hoping your timew-report library would help me write custom reports with annotations :)

**Comment by ahillio** [comment]
Oh I just found https://github.com/lauft/timew-report/commit/f8d6cf4c60228a84217e1e5de640c79d8cae0973

**Comment by ahillio** [comment]
Is this available via `pip` yet?  I just just did `pip3 install timew-report --upgrade` but it says 

```
Requirement already up-to-date: timew-report in /home/alec/.local/lib/python3.7/site-packages (1.0.2)
Requirement already satisfied, skipping upgrade: python-dateutil in /home/alec/.local/lib/python3.7/site-packages (from timew-report) (2.8.1)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->timew-report) (1.12.0)
```

and I don't seem to be able to access annotations as `interval.get_annotation()` produces an error saying ther'es no 'annotation' attribute.

**Comment by ahillio** [comment]
Oh yes :)
`pip install git+https://github.com/lauft/timew-report.git@f8d6cf4c60228a84217e1e5de640c79d8cae0973` for any pip newbies wondering by.

Thanks for this software @lauft !

**Comment by lauft** [comment]
> Is this available via pip yet?

@ahillio Working towards it, please be patient.

**Comment by lauft** [comment]
@ahillio `timew-report` `1.3.0` has just been released on pypi.
